// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3L3FB2-xQcvPqirWSZl9J77ow9opCjxE',
    appId: '1:480609385955:web:c775e9d7f1ee65a5fbf4d6',
    messagingSenderId: '480609385955',
    projectId: 'uffcaronasg5-a4a64',
    authDomain: 'uffcaronasg5-a4a64.firebaseapp.com',
    storageBucket: 'uffcaronasg5-a4a64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVBPoq30fPBwU8wRWiPj7moQmfyhQBxo',
    appId: '1:480609385955:android:8d3c2e166fec04adfbf4d6',
    messagingSenderId: '480609385955',
    projectId: 'uffcaronasg5-a4a64',
    storageBucket: 'uffcaronasg5-a4a64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6Vw2l_3ywou6iihJi5sh-Hf0_QATLRQ',
    appId: '1:480609385955:ios:98ddf096927c0e0cfbf4d6',
    messagingSenderId: '480609385955',
    projectId: 'uffcaronasg5-a4a64',
    storageBucket: 'uffcaronasg5-a4a64.appspot.com',
    androidClientId: '480609385955-78j1sit69t6v2m7gjj9lcr99sbga9n28.apps.googleusercontent.com',
    iosClientId: '480609385955-vgkon8lvb9tvaolb37h1snvskpfoqiol.apps.googleusercontent.com',
    iosBundleId: 'com.example.uffCaronas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe6Vw2l_3ywou6iihJi5sh-Hf0_QATLRQ',
    appId: '1:480609385955:ios:98ddf096927c0e0cfbf4d6',
    messagingSenderId: '480609385955',
    projectId: 'uffcaronasg5-a4a64',
    storageBucket: 'uffcaronasg5-a4a64.appspot.com',
    androidClientId: '480609385955-78j1sit69t6v2m7gjj9lcr99sbga9n28.apps.googleusercontent.com',
    iosClientId: '480609385955-vgkon8lvb9tvaolb37h1snvskpfoqiol.apps.googleusercontent.com',
    iosBundleId: 'com.example.uffCaronas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3L3FB2-xQcvPqirWSZl9J77ow9opCjxE',
    appId: '1:480609385955:web:98369ce6c89f20ddfbf4d6',
    messagingSenderId: '480609385955',
    projectId: 'uffcaronasg5-a4a64',
    authDomain: 'uffcaronasg5-a4a64.firebaseapp.com',
    storageBucket: 'uffcaronasg5-a4a64.appspot.com',
  );

}